#!/usr/bin/env node

/**
 * Figma Variables JSON → tokens.css sync script
 *
 * Usage:
 *   node scripts/sync-tokens.mjs
 *   node scripts/sync-tokens.mjs path/to/variables.json
 *
 * Reads the exported JSON from Figma (default: all_color_variables.json)
 * and generates app/src/styles/tokens.css with all color + typography tokens.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DEFAULT_INPUT = resolve(ROOT, 'all_color_variables.json');
const OUTPUT = resolve(ROOT, 'app/src/styles/tokens.css');

const inputPath = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_INPUT;

// Read and parse
let variables;
try {
  variables = JSON.parse(readFileSync(inputPath, 'utf-8'));
  console.log(`Read ${variables.length} variables from ${inputPath}`);
} catch (err) {
  console.error(`Error reading ${inputPath}: ${err.message}`);
  console.error('Export your Figma variables as JSON and save as all_color_variables.json');
  process.exit(1);
}

function slugify(name) {
  return name
    .split('/')
    .map((s) => s.trim().toLowerCase().replace(/\s+/g, '-'))
    .join('-');
}

// Separate primitives and semantic tokens by collection/mode
const primitives = variables
  .filter((v) => v.collection === 'Primitives')
  .map((v) => {
    const parts = v.name.split('/');
    const group = parts.length > 1 ? parts[0] : 'Gray';
    return {
      name: `--primitive-${slugify(v.name)}`,
      value: v.hex.toLowerCase(),
      group,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const semanticByMode = {};
for (const v of variables) {
  if (v.collection !== 'Punch DDS') continue;
  if (!semanticByMode[v.mode]) semanticByMode[v.mode] = [];
  semanticByMode[v.mode].push({
    name: `--${slugify(v.name)}`,
    value: v.hex.toLowerCase(),
    group: v.name.split('/')[0],
  });
}
for (const mode of Object.keys(semanticByMode)) {
  semanticByMode[mode].sort((a, b) => a.name.localeCompare(b.name));
}

// Group helper
function renderGrouped(vars, indent = '  ') {
  const groups = new Map();
  for (const v of vars) {
    if (!groups.has(v.group)) groups.set(v.group, []);
    groups.get(v.group).push(v);
  }
  const lines = [];
  for (const [group, items] of groups) {
    lines.push(`${indent}/* ${group} */`);
    for (const item of items) {
      lines.push(`${indent}${item.name}: ${item.value};`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// Type scale (hardcoded — update when Figma text styles change)
const typeScale = [
  { cat: 'heading', size: 'h1', px: 28, lh: 36 },
  { cat: 'heading', size: 'h2', px: 24, lh: 32 },
  { cat: 'body', size: 'b1', px: 18, lh: 24 },
  { cat: 'body', size: 'b2', px: 16, lh: 20 },
  { cat: 'body', size: 'b3', px: 14, lh: 18 },
  { cat: 'body', size: 'b4', px: 12, lh: 16 },
  { cat: 'caption', size: 'c1', px: 10, lh: null },
  { cat: 'caption', size: 'c2', px: 9, lh: null },
  { cat: 'caption', size: 'c3', px: 8, lh: 10 },
];
const weights = [
  { name: 'bold', value: 700 },
  { name: 'semibold', value: 600 },
  { name: 'medium', value: 500 },
  { name: 'regular', value: 400 },
];

// Build CSS
const lines = [];

lines.push('/**');
lines.push(' * Design tokens from the Punch Desktop Design System Figma Variables.');
lines.push(' * Auto-generated by scripts/sync-tokens.mjs — do not edit by hand.');
lines.push(' * Source: https://www.figma.com/design/y1hJPuNFlUlkgYIYfVL2k5/Punch-Desktop-Design-System');
lines.push(' */');
lines.push('');
lines.push(':root {');

// Primitives
lines.push('  /* ═══════════════════════════════════════════════════════');
lines.push('     Primitives — raw color palette');
lines.push('     ═══════════════════════════════════════════════════════ */');
lines.push('');
lines.push(renderGrouped(primitives));

// Default semantic theme (Dark)
if (semanticByMode['Dark']) {
  lines.push('  /* ═══════════════════════════════════════════════════════');
  lines.push('     Punch DDS — semantic tokens (Dark theme = default)');
  lines.push('     ═══════════════════════════════════════════════════════ */');
  lines.push('');
  lines.push(renderGrouped(semanticByMode['Dark']));
}

// Component aliases
lines.push('  /* ═══════════════════════════════════════════════════════');
lines.push('     Component aliases — backward-compatible names used by');
lines.push('     existing components (Button, etc.) mapped to primitives');
lines.push('     ═══════════════════════════════════════════════════════ */');
lines.push('');
lines.push('  --buttons-bg-success: var(--primitive-green-400);');
lines.push('  --buttons-bg-error: var(--primitive-red-300);');
lines.push('  --buttons-bg-pending: var(--primitive-orange-300);');
lines.push('  --buttons-bg-secondary-cta: var(--primitive-black-and-white-white);');
lines.push('  --buttons-bg-tertiary: var(--primitive-neutral-700);');
lines.push('  --buttons-outline-secondary-cta: var(--primitive-black-and-white-white);');
lines.push('  --buttons-text-primary: var(--primitive-neutral-1000);');
lines.push('');
lines.push('  --outline-success: var(--primitive-green-400);');
lines.push('  --outline-error: var(--primitive-red-300);');
lines.push('  --outline-pending: var(--primitive-orange-300);');
lines.push('  --outline-on-primary: var(--primitive-black-and-white-white);');
lines.push('');
lines.push('  --green-1500: var(--primitive-green-1500);');
lines.push('  --red-100: var(--primitive-red-100);');
lines.push('  --orange-100: var(--primitive-orange-100);');
lines.push('  --neutral-200: var(--primitive-neutral-200);');
lines.push('');
lines.push('  --bg-main-page-primary: var(--primitive-neutral-1000);');
lines.push('');

// Typography
lines.push('  /* ═══════════════════════════════════════════════════════');
lines.push('     Typography — all text styles from Figma');
lines.push('     ═══════════════════════════════════════════════════════ */');
lines.push('');
lines.push("  --font-family-base: 'Inter', system-ui, sans-serif;");
lines.push('');
for (const t of typeScale) {
  lines.push(`  /* ${t.cat.charAt(0).toUpperCase() + t.cat.slice(1)} / ${t.size.toUpperCase()} — ${t.px}px / ${t.lh ? t.lh + 'px' : 'auto'} */`);
  for (const w of weights) {
    const prefix = `--font-${t.cat}-${t.size}-${w.name}`;
    lines.push(`  ${prefix}-size: ${t.px}px;`);
    lines.push(`  ${prefix}-line-height: ${t.lh ? t.lh + 'px' : 'normal'};`);
    lines.push(`  ${prefix}-weight: ${w.value};`);
    lines.push('');
  }
}

lines.push('}');

// Theme overrides
const themeSelectors = {
  Light: '[data-theme="light"]',
  'Deep Black': '[data-theme="deep-black"]',
};

for (const [mode, selector] of Object.entries(themeSelectors)) {
  if (!semanticByMode[mode]) continue;
  lines.push('');
  lines.push('/* ═══════════════════════════════════════════════════════');
  lines.push(`   ${mode} theme`);
  lines.push('   ═══════════════════════════════════════════════════════ */');
  lines.push(`${selector} {`);
  lines.push('');
  lines.push(renderGrouped(semanticByMode[mode]));
  lines.push('}');
}

const css = lines.join('\n') + '\n';

writeFileSync(OUTPUT, css, 'utf-8');

// Summary
const primCount = primitives.length;
const semCounts = Object.entries(semanticByMode)
  .map(([mode, vars]) => `${mode}: ${vars.length}`)
  .join(', ');
const typoCount = typeScale.length * weights.length * 3;

console.log(`\nGenerated ${OUTPUT}`);
console.log(`  Primitives: ${primCount}`);
console.log(`  Semantic: ${semCounts}`);
console.log(`  Typography: ${typoCount} properties (${typeScale.length} sizes x ${weights.length} weights)`);
console.log(`  Component aliases: 16`);
console.log(`\nTotal CSS custom properties: ${primCount + Object.values(semanticByMode).reduce((s, v) => s + v.length, 0) + typoCount + 16 + 1}`);
